name: deltaplan_app
description: "Мобильное и веб приложение для платформы Дельтаплан."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  table_calendar: ^3.1.2
  
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  universal_io: ^2.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true