services:
  postgres:
    image: postgres:15-alpine
    container_name: deltaplan_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    restart: always
    networks:
      - deltaplan_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deltaplan_backend_prod
    command: gunicorn deltaplan.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - postgres
    restart: always
    networks:
      - deltaplan_net

  nginx:
    image: nginx:1.25-alpine
    container_name: deltaplan_nginx_prod
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
    restart: always
    networks:
      - deltaplan_net
    logging:
      driver: "none"

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

networks:
  deltaplan_net:
    driver: bridge