volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

services:
  postgres:
    container_name: deltaplan_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports: []
    restart: always
    networks:
      - deltaplan_net

  backend:
    container_name: deltaplan_backend_prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports: []
    command: gunicorn deltaplan.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    restart: always
    networks:
      - deltaplan_net

  nginx:
    image: nginx:1.25-alpine
    container_name: deltaplan_nginx_prod
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
    restart: always
    networks:
      - deltaplan_net