services:
  postgres_prod:
    image: postgres:15-alpine
    container_name: deltaplan_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ./backend/.env_prod
    restart: always
    networks:
      - deltaplan_net_prod

  backend_prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deltaplan_backend_prod
    command: gunicorn deltaplan.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - static_volume:/app/deltaplan/static
      - media_volume:/app/deltaplan/media
    env_file:
      - ./backend/.env_prod
    depends_on:
      - postgres_prod
    restart: always
    networks:
      - deltaplan_net_prod

  nginx:
    image: nginx:1.25-alpine
    container_name: deltaplan_nginx_prod
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/deltaplan/static:ro
      - media_volume:/app/deltaplan/media:ro
      - ./frontend/build/web:/usr/share/nginx/html:ro
    depends_on:
      - backend_prod
    restart: always
    networks:
      - deltaplan_net_prod

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:

networks:
  deltaplan_net_prod:
    driver: bridge
    name: deltaplan_net_prod
