services:
  postgres_dev:
    image: postgres:15-alpine
    container_name: deltaplan_db_dev
    env_file:
      - ./backend/.env
    ports:
      - "8082:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - deltaplan_net_dev

  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deltaplan_backend_dev
    working_dir: /app/deltaplan
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres_dev:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - deltaplan_net_dev

volumes:
  postgres_data_dev:

networks:
  deltaplan_net_dev:
    driver: bridge
    name: deltaplan_net_dev
