# Generated by Django 5.2.1 on 2025-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentschoolregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("approved", "Одобрена"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("approved", "Одобрена"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
