# Generated by Django 5.2.1 on 2025-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_parentschoolregistration_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="theaterrole",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("assigned", "Assigned")],
                default="open",
                max_length=20,
            ),
        ),
    ]
